### ISSUE TITLE
Total number of epochs

### ISSUE THREAD

**Issue by absqh** [ChenHongruixuan/MambaCD#48]
Could you please tell me what are the approximate epochs of the three datasets in the BCD task?

**Comment by ChenHongruixuan** [comment]
Hi, 

Please refer to our paper: 

> The batch size is set to 16. Except for the SYSU dataset, for which we set the number of training iterations to 20000, we set the number of training iterations to 50000 on the remaining four datasets.

**Comment by absqh** [comment]
Hello, I saw this, but most of the training settings in the paper are presented in epochs. I would like to know what the corresponding epoch is. I don't quite understand their correspondence.

**Comment by ChenHongruixuan** [comment]
Hi,

You can get the so-called epoch number by batch size * iteration_num / training_num. But I would like to remind you that the number of epochs I think of is the number of times the model has seen all the samples. But since we use random cropping, the model only sees part of each sample each time. So I don't think it makes much sense to keep the epoch number consistent with other work here.

Best,
