### ISSUE TITLE
NameError: name 'selective_scan_cuda_oflex' is not defined

### ISSUE THREAD

**Issue by fengfeng-xie** [ChenHongruixuan/MambaCD#75]
How to solve this problem：NameError: name 'selective_scan_cuda_oflex' is not defined？Do you solve this proble？Please tell me.Thank
you!

**Comment by ChenHongruixuan** [comment]
Hi, thank you so much for your interest to our work. Please refer to our common issue section. There is a link to relevant solutions. And also you can find relevant solutions directly in the issue section. Generally, it is caused by that your pytorch and CUDA versions do not meet the requirements (requiring 11.6 or higher). We also recommend you to refer to the VMamba repo to get relevant solutions.

**Comment by ChenHongruixuan** [comment]
Hi @fengfeng-xie ,

May I ask have you solved this problem? 

Best,

**Comment by fengfeng-xie** [comment]
> 您好 ，
> 
> 请问你解决了这个问题吗？
> 
> 最好

I'm in graduate school and I'm currently only working at the level of reproducing code, I don't know how to go about researching or innovating, can you give me some advice? Would like to invest in this area of unsupervised change detection.

**Comment by ChenHongruixuan** [comment]
Hi @fengfeng-xie ,


> no,I don't know if this code can run in the System of Windows?My CUDA is 11.3,I have not update it.

Please take a look at the VMamba repo to see if it can be run in the Windows system.

> I'm in graduate school and I'm currently only working at the level of reproducing code, I don't know how to go about researching or innovating, can you give me some advice? Would like to invest in this area of unsupervised change detection.

Sure. You can send questions to my email. 

Best,
